---
name: Code analysis
on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  sonarcloud:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest" ] #, "macos-latest", "windows-latest"]
        python-version: ["3.11"] # fix tests to support older versions
        include:
          - os: ubuntu-latest
            label: linux-64

    name: SonarCloud
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Restore coverage report
        uses: actions/download-artifact@v2
        with:
          name: coverage ${{ matrix.python-version }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
